# Generated by Django 5.0.2 on 2024-02-21 02:24

import chat.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='from_user',
        ),
        migrations.AddField(
            model_name='message',
            name='message_type',
            field=models.IntegerField(choices=[(chat.models.MessageType['USER'], 'USER'), (chat.models.MessageType['CHATBOT'], 'CHATBOT'), (chat.models.MessageType['SYSTEM'], 'SYSTEM')], default=chat.models.MessageType['USER']),
        ),
    ]
