# Generated by Django 5.0.2 on 2024-03-26 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_remove_message_from_user_message_message_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatRequestGeoData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('request_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
