# Generated by Django 5.0.2 on 2024-04-22 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_chatrequestgeodata'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatrequestgeodata',
            name='county',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
